version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: stage
      MYSQL_USER: admin
      MYSQL_PASSWORD: 12345
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./mariadb-config:/etc/mysql/conf.d

volumes:
  mariadb_data:
