import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "../../node_modules/next/link";
import "./globals.css";


//components
import Navbar from './components/navbar'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />

        {children}
        </body>
    </html>
  );
}
